version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    env_file:
      - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend-terr-zoo
    restart: unless-stopped
    build:
      context: ./docker/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: frontend-terr-zoo
    restart: unless-stopped
    build:
      context: ./docker/frontend
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
  redis:
    image: redis:6.0.16-alpine
    restart: unless-stopped
volumes:
  react_build:
  pgdata: