# Generated by Django 4.0.5 on 2022-08-11 09:53

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название животного')),
                ('image', models.ImageField(blank=True, upload_to='photos_animal/Y/M/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тип животного',
                'verbose_name_plural': 'ТИПЫ ЖИВОТНЫХ',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название бренда')),
                ('image', models.ImageField(blank=True, upload_to='photos_brand/Y/M/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'БРЕНДЫ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'КАТЕГОРИИ',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=100, verbose_name='Автор отзыва')),
                ('body_of_comment', models.TextField(verbose_name='Содержание отзыва')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('name_animal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя питомца')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв о магазине',
                'verbose_name_plural': 'ОТЗЫВЫ О МАГАЗИНЕ',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)], verbose_name='Номер телефона')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Кол-во заявок от этого покупателя')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'КОНСУЛЬТАЦИЯ',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя покупателя')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефона')),
                ('first_order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата первого заказа')),
            ],
            options={
                'verbose_name': 'ПОКУПАТЕЛЬ',
                'verbose_name_plural': 'ПОКУПАТЕЛИ',
                'ordering': ('first_order_date',),
            },
        ),
        migrations.CreateModel(
            name='InfoShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес магазина')),
                ('metro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Станция метро')),
                ('time_weekdays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы (будние)')),
                ('time_weekend', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы (выходные)')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('social', models.TextField(blank=True, help_text='Ссылка на страницу', null=True, verbose_name='Социальная сеть')),
                ('maps', models.TextField(blank=True, help_text='Ссылка с яндекс карты (размер 670х374)', verbose_name='Расположение на карте')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото режима работы')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголов описания')),
                ('main_info', models.TextField(blank=True, null=True, verbose_name='Тело описания')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'О магазине',
                'verbose_name_plural': 'О МАГАЗИНЕ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заказа')),
                ('paid', models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')], default=0, verbose_name='Оплачен')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'ЗАКАЗ',
                'verbose_name_plural': 'ЗАКАЗЫ',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название товара')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание товара')),
                ('features', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ключевые особенности')),
                ('composition', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Состав')),
                ('additives', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Пищевые добавки')),
                ('analysis', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Гарантированный анализ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('popular', models.IntegerField(choices=[(0, 'Стандартный'), (1, 'Популярный'), (2, 'Очень популярный')], default=0, verbose_name='Популярность')),
                ('animal', models.ManyToManyField(blank=True, related_name='products', to='main.animal', verbose_name='Тип животного')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'ТОВАРЫ',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Ед. измерения')),
            ],
            options={
                'verbose_name': 'Еденица измерения',
                'verbose_name_plural': 'ЕДИНИЦЫ ИЗМЕРЕНИЯ',
            },
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Артикул товара')),
                ('partial', models.BooleanField(default=False, verbose_name='На развес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('size', models.IntegerField(verbose_name='Объём упаковки')),
                ('stock_balance', models.PositiveIntegerField(verbose_name='Остаток на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.product', verbose_name='Варианты')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='main.units', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Вариант фасовки',
                'verbose_name_plural': 'ВАРИАНТЫ ФАСОВКИ',
                'ordering': ('partial', 'size'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos_products/Y/M/', verbose_name='Изображение товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'ИЗОБРАЖЕНИЕ ТОВАРА',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('article_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.productoptions', to_field='article_number', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'ЗАКАЗАННЫЙ ТОВАР',
                'verbose_name_plural': 'ЗАКАЗАННЫЕ ТОВАРЫ',
            },
        ),
        migrations.CreateModel(
            name='InfoShopBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок Блока')),
                ('info_text', models.TextField(blank=True, null=True, verbose_name='Описание Блока')),
                ('info_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_info', to='main.infoshop', verbose_name='О магазине')),
            ],
            options={
                'verbose_name': 'Блок о магазине',
                'verbose_name_plural': 'БЛОКИ О МАГАЗИНЕ',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание статьи')),
                ('image', models.ImageField(blank=True, upload_to='photos_article/Y/M/', verbose_name='Изображение')),
                ('time_read', models.CharField(max_length=50, verbose_name='Время чтения статьи')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления статьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.animal', verbose_name='Название животного')),
            ],
            options={
                'verbose_name': 'Полезная статья',
                'verbose_name_plural': 'ПОЛЕЗНЫЕ СТАТЬИ',
                'ordering': ['-date_added'],
            },
        ),
    ]
