# Generated by Django 4.0.5 on 2022-08-11 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discountproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название/Описание скидки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('discount_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='% Скидки в диапазоне - [1-90]')),
                ('product_option', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_option', to='main.productoptions', verbose_name='Вариант Фасовки')),
            ],
            options={
                'verbose_name': 'Скидка на вариант фасовки',
                'verbose_name_plural': 'Скидки на варианты фасовки',
            },
        ),
        migrations.CreateModel(
            name='DiscountByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название/Описание скидки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('discount_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='% Скидки в диапазоне - [1-90]')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_category', to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
