# Generated by Django 4.0.7 on 2022-08-16 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comments_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Название/Описание скидки')),
                ('days_discount', models.CharField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресение')], default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Дни недели для скидки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'ЖИВОТНОГО', 'verbose_name_plural': 'ЖИВОТНЫЕ'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'БРЕНД', 'verbose_name_plural': 'БРЕНДЫ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'КАТЕГОРИИ', 'verbose_name_plural': 'КАТЕГОРИИ'},
        ),
        migrations.AlterModelOptions(
            name='discountbycategory',
            options={'verbose_name': 'СКИДКА НА ТОВАР', 'verbose_name_plural': 'СКИДКИ НА ТОВАРЫ'},
        ),
        migrations.AlterModelOptions(
            name='discountproduct',
            options={'verbose_name': 'СКИДКА НА ТОВАР', 'verbose_name_plural': 'СКИДКИ НА ТОВАРЫ'},
        ),
        migrations.AlterModelOptions(
            name='discountproductoption',
            options={'verbose_name': 'Скидка на фасовку товара', 'verbose_name_plural': 'СКИДКИ НА ВАРИАНТЫ ФАСОВКИ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'ПРОДУКТ', 'verbose_name_plural': 'ПРОДУКТЫ'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_animal/Y/M/', verbose_name='Изображение животного'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_article/Y/M/', verbose_name='Изображение бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_brand/Y/M/', verbose_name='Изображение бренда'),
        ),
        migrations.AlterField(
            model_name='discountbycategory',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Процент скидки не должен быть меньше 1% и превышать 90%', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Процент скидки не должен быть меньше 1% и превышать 90%', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_product', to='main.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='discountproductoption',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Процент скидки не должен быть меньше 1% и превышать 90%', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='infoshop',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_time/Y/M/', verbose_name='Фото режима работы'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_products/Y/M/', verbose_name='Изображение товара'),
        ),
        migrations.CreateModel(
            name='DiscountByDayOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price_for_discount', models.PositiveIntegerField(verbose_name='Сумма покупок, от которой считается скидка')),
                ('discount_amount', models.PositiveIntegerField(default=0, help_text='Процент скидки не должен быть меньше 1% и превышать 90%', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Процент скидки')),
                ('discount_by_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.discountbyday')),
            ],
        ),
    ]
