# Generated by Django 4.0.7 on 2022-08-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_discountbyday_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountbyday',
            name='days_discount',
        ),
    ]
