# Generated by Django 4.0.7 on 2022-08-16 12:09

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_discountbyday_days_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountByDayWeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_discount', models.CharField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресение')], default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Дни недели для скидки')),
                ('discount_by_day', models.ManyToManyField(related_name='week_days', to='main.discountbyday', verbose_name='Дни недели')),
            ],
        ),
    ]
