# Generated by Django 4.0.7 on 2022-08-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_discountbydayweekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountbydayweekdays',
            name='days_discount',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресение')], null=True, verbose_name='Дни недели для скидки'),
        ),
    ]
