# Generated by Django 4.0.7 on 2022-08-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_discountbydayweekdays_days_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountbydayweekdays',
            name='discount_by_day',
        ),
    ]
