# Generated by Django 4.0.7 on 2022-08-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_discountbydayweekdays_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountbyday',
            name='week_days',
            field=models.ManyToManyField(related_name='discount_by_day', to='main.weekdays', verbose_name='Дни недели'),
        ),
    ]
