# Generated by Django 4.0.7 on 2022-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_discountbyday_week_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountbyday',
            options={'verbose_name': 'Скидка по дням недели', 'verbose_name_plural': 'Скидки по дням недели'},
        ),
        migrations.AlterModelOptions(
            name='discountbydayoptions',
            options={'verbose_name': 'Сумма покупок для скидки и размер скидки', 'verbose_name_plural': 'СУММЫ ПОКУПОК ДЛЯ СКИДОК И РАЗМЕР СКИДОК'},
        ),
        migrations.AlterModelOptions(
            name='weekdays',
            options={'verbose_name': 'День недели для скидки', 'verbose_name_plural': 'Дни недели для скидок'},
        ),
        migrations.AlterField(
            model_name='discountbyday',
            name='title',
            field=models.TextField(max_length=250, null=True, verbose_name='Название/Описание скидки'),
        ),
        migrations.AlterField(
            model_name='discountbyday',
            name='week_days',
            field=models.ManyToManyField(related_name='discount_by_day', to='main.weekdays', verbose_name='Дни недели для скидки'),
        ),
    ]
