# Generated by Django 4.0.7 on 2022-08-18 10:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_discountbyday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoshop',
            name='personal_data_politics',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Политика в отношении обработки персональных данных'),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.product', verbose_name='Варианты фасовки'),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Создайте новую единицу измерения (шт. л. кг. и тд.) если её нету в списке', max_length=50, null=True, verbose_name='Название единиц измерения'),
        ),
    ]
