# Generated by Django 4.0.7 on 2022-08-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_infoshop_personal_data_politics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoShopMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100, null=True, verbose_name='Главный блок')),
                ('option_one', models.CharField(max_length=50, null=True, verbose_name='Первый блок')),
                ('option_two', models.CharField(max_length=50, null=True, verbose_name='Второй блок')),
                ('info_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_main_page', to='main.infoshop', verbose_name='Информация на главной странице')),
            ],
        ),
    ]
