# Generated by Django 4.0.7 on 2022-08-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_infoshopmainpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoshopmainpage',
            options={'verbose_name': 'Информация на главной странице о магазине'},
        ),
    ]
