# Generated by Django 4.0.7 on 2022-08-18 11:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_infoshopmainpage_main_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoshopmainpage',
            name='main_title',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Главный блок'),
        ),
        migrations.AlterField(
            model_name='infoshopmainpage',
            name='option_one',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Первый блок'),
        ),
        migrations.AlterField(
            model_name='infoshopmainpage',
            name='option_two',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Второй блок'),
        ),
    ]
