# Generated by Django 4.0.7 on 2022-08-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_infoshopmainpage_main_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountbydayoptions',
            options={'ordering': ('-min_price_for_discount',), 'verbose_name': 'Сумма покупок для скидки и размер скидки', 'verbose_name_plural': 'СУММЫ ПОКУПОК ДЛЯ СКИДОК И РАЗМЕР СКИДОК'},
        ),
        migrations.RemoveField(
            model_name='discountbyday',
            name='week_days',
        ),
    ]
