# Generated by Django 4.0.7 on 2022-08-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_discountbydayoptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdays',
            name='discount_by_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_days', to='main.discountbyday'),
        ),
    ]
