# Generated by Django 4.0.7 on 2022-08-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_weekdays_discount_by_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='discount_by_day',
        ),
    ]
