# Generated by Django 4.0.7 on 2022-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_weekdays_discount_by_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountbyday',
            name='week_days',
            field=models.ManyToManyField(related_name='discount_by_day', to='main.weekdays', verbose_name='Дни недели для скидки'),
        ),
    ]
