# Generated by Django 4.0.7 on 2022-08-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_discountbyday_week_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoshopmainpage',
            name='info_shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_main_page', to='main.infoshop', verbose_name='Информация на главной странице'),
        ),
    ]
