# Generated by Django 4.0.7 on 2022-08-19 12:47

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_infoshopmainpage_info_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Описание баннера')),
                ('background_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_banner/background/Y/M/', verbose_name='Фоновое изображение')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_banner/image/Y/M/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
        ),
    ]
