# Generated by Django 4.0.7 on 2022-08-20 10:58

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Рекламный Баннер', 'verbose_name_plural': 'РЕКЛАМНЫЕ БАННЕРЫ'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_image',
        ),
        migrations.AddField(
            model_name='banner',
            name='color',
            field=colorfield.fields.ColorField(default='#30FFE9', help_text='Выберите цвет для фона баннера', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Для загрузки изображения с фоном баннера, загружайте файлы в формате PNG', null=True, upload_to='photos_banner/image/Y/M/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.product', verbose_name='Название товара'),
        ),
    ]
