# Generated by Django 4.0.7 on 2022-08-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_banner_info_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='info_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.infoshop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
