# Generated by Django 4.0.7 on 2022-08-21 19:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_banner_info_shop_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_animal/', verbose_name='Изображение животного'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_article/', verbose_name='Изображение бренда'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Для загрузки изображения с фоном баннера, загружайте файлы в формате PNG', null=True, upload_to='photos_banner/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_brand/', verbose_name='Изображение бренда'),
        ),
        migrations.AlterField(
            model_name='infoshop',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_time/', verbose_name='Фото режима работы'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_products/', verbose_name='Изображение товара'),
        ),
    ]
