# Generated by Django 4.0.7 on 2022-08-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_animal_image_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoshop',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок описания'),
        ),
    ]
