# Generated by Django 4.0.7 on 2022-08-22 08:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_infoshop_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoshopmainpage',
            name='photo_main_page',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos_main_page/', verbose_name='Фото на главной странице'),
        ),
    ]
