# Generated by Django 4.0.7 on 2022-08-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_infoshopmainpage_photo_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего заказа'),
        ),
    ]
