# Generated by Django 4.0.7 on 2022-08-23 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_customer_last_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата последнего заказа'),
        ),
    ]
