# Generated by Django 4.0.7 on 2022-08-23 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_customer_last_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего заказа'),
        ),
    ]
