# Generated by Django 4.0.7 on 2022-08-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_order_total_sum_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Сумма Заказа с возможными скидками'),
        ),
    ]
