# Generated by Django 4.0.7 on 2022-08-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_order_total_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
