# Generated by Django 4.0.7 on 2022-08-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_name_consultation_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='counter',
        ),
        migrations.AddField(
            model_name='consultation',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обращения'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата первого обращения'),
        ),
    ]
