# Generated by Django 4.0.7 on 2022-08-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_consultation_counter_consultation_date_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='covered',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
