# Generated by Django 4.0.7 on 2022-08-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_order_covered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='covered',
        ),
    ]
