# Generated by Django 4.0.7 on 2022-08-25 16:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_order_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='info_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.infoshop'),
        ),
        migrations.RemoveField(
            model_name='discountbyday',
            name='week_days',
        ),
        migrations.AddField(
            model_name='discountbyday',
            name='week_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресение')], null=True), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='WeekDays',
        ),
    ]
