# Generated by Django 4.0.7 on 2022-08-27 00:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_banner_info_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[main.models.phone_validator], verbose_name='Номер телефона'),
        ),
    ]
