# Generated by Django 4.0.7 on 2022-08-27 00:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_consultation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[main.models.phone_validator], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[main.models.phone_validator], verbose_name='Номер телефона'),
        ),
    ]
